global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['prometheus:9090']
- job_name: 'spring'
  metrics_path: '/api/actuator/prometheus'
  static_configs:
  - targets: ['spring-app:8080']
- job_name: 'sonarqube'
  metrics_path: '/api/monitoring/metrics'
  static_configs:
  - targets: ['sonarqube:9000']
  basic_auth:
    username: "admin"
    password: "adminsonar"